### PR TITLE
Remove trailing \r from raw line, in presence of ANSI escape sequences

### LINKED ISSUE #795: 🐛 git's --color-moved with DOS line endings (\r\n) triggers a panic
Using delta 92d6591e and git version 2.30.2. To reproduce:

    $ echo -e "move_this_long_function()\\nfoo()\\nbar()" | sed 's,$,\r,' > a.py
    $ { tail -n 2 a.py; head -n 1 a.py; } > b.py 
    $ git diff --color-moved --no-index --color=always a.py b.py | target/release/delta --no-gitconfig 
    
    thread 'main' panicked at 'String mismatch encountered while superimposing style sections: '
    '', src/paint.rs:921:17
    
    [..]
    2: delta::paint::superimpose_style_sections::superimpose_style_sections
    3: delta::paint::Painter::paint_line
    4: delta::paint::Painter::paint_buffered_minus_and_plus_lines
    5: delta::delta::delta
    6: delta::main
    $ cat -A a.py
    move_this_long_function()^M$
    foo()^M$
    bar()^M$

### PR DESCRIPTION
**Pull request by dandavison**
Fixes #795 cc @th1000s

### CODE REVIEW

File: src/delta.rs [hunk 1]
```diff
@@ -152,13 +163,6 @@ impl<'a> StateMachine<'a> {
...
         };
         self.line = ansi::strip_ansi_codes(&self.raw_line);
-
-        // Strip the neglected CR.
-        // (CR-LF is unfortunately split by git because it adds ansi escapes between them.
-        //  Thus byte_lines library can't remove the CR properly.)
-        if let Some(b'\r') = self.line.bytes().nth_back(0) {
-            self.line.truncate(self.line.len() - 1);
-        }
     }
```
Comment (dandavison) [inline src/delta.rs:166]: I owe some tests, but we can see that with this commit we are still fixing the `git add -p` pbug that was the reason for the addition of the lines above (now deleted and replaced by the lines further above):

```
git add a.py && git commit -m .
mv b.py a.py
```

Without any \r-stripping, notice that one of the lines is not rendered due to the \r:

<table><tr><td>image</td></tr></table> 
With the code after this commit:

<table><tr><td>image</td></tr></table>
