### PR TITLE
Fix panicking when diffing filenames with space enclosed dashes

### LINKED ISSUE #139: Diff for filenames with space enclosed dashes panic
## What should happen:
diffs for files with space enclosed dashes should work
## What does happen:
diffs for files with space enclosed dashes cause panicking

## How to reproduce:
git-delta is installed from cargo with
```
cargo install git-delta --debug
```

I've set up delta for git in `.gitconfig` as given in [README.md](https://github.com/dandavison/delta#configure-git-to-use-delta)

Setup:
```bash
# create a test git
git init test
cd test

# create a file with space enclosed dash
echo "test" > "strange - file.txt"
git add strange\ -\ file.txt
```

diff panics with this:
<details>
<summary>Backtrace...</summary>
<p>

```bash session
$ RUST_BACKTRACE=full git diff --cached
thread 'main' panicked at 'byte index 2 is out of bounds of `-`', /rustc/2113659479a82ea69633b23ef710b58ab127755e/src/libcore/str/mod.rs:2052:47
stack backtrace:
   0:     0x563bf4cca994 - backtrace::backtrace::libunwind::trace::h70b375bde27270b4
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x563bf4cca994 - backtrace::backtrace::trace_unsynchronized::h396dd4a8c22b105f
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x563bf4cca994 - std::sys_common::backtrace::_print_fmt::he18b870d0c222866
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x563bf4cca994 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb01a2733282e3ed2
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x563bf4cf3e6c - core::fmt::write::h90106c9d994b1fcb
                               at src/libcore/fmt/mod.rs:1069
   5:     0x563bf4cc8293 - std::io::Write::write_fmt::hda3987c08ec43d0b
                               at src/libstd/io/mod.rs:1439
   6:     0x563bf4ccd0d5 - std::sys_common::backtrace::_print::h0fc3670894ce6aaa
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x563bf4ccd0d5 - std::sys_common::backtrace::print::haa35adc6f414ffd2
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x563bf4ccd0d5 - std::panicking::default_hook::{{closure}}::ha7d6a7d9f72f7b9b
                               at src/libstd/panicking.rs:198
   9:     0x563bf4ccce12 - std::panicking::default_hook::hc8bfdfb3de37ef02
                               at src/libstd/panicking.rs:218
  10:     0x563bf4ccd732 - std::panicking::rust_panic_with_hook::h4fd82df629484fe1
                               at src/libstd/panicking.rs:511
  11:     0x563bf4ccd31b - rust_begin_unwind
                               at src/libstd/panicking.rs:419
  12:     0x563bf4cf2891 - core::panicking::panic_fmt::ha6a1c3f81a836c59
                               at src/libcore/panicking.rs:111
  13:     0x563bf4cf6eaa - core::str::slice_error_fail::h0ec47dff71c3969c
                               at src/libcore/str/mod.rs:0
  14:     0x563bf4c925e7 - core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::RangeFrom<usize>>::index::{{closure}}::haf32b64db81a53f5
                               at /rustc/2113659479a82ea69633b23ef710b58ab127755e/src/libcore/str/mod.rs:2052
  15:     0x563bf4c8a7f1 - core::option::Option<T>::unwrap_or_else::h1f8e4dd28a69aa32
                               at /rustc/2113659479a82ea69633b23ef710b58ab127755e/src/libcore/option.rs:428
  16:     0x563bf4c92591 - core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::RangeFrom<usize>>::index::h477e406a2a37d089
                               at /rustc/2113659479a82ea69633b23ef710b58ab127755e/src/libcore/str/mod.rs:2052
  17:     0x563bf4c92762 - core::str::traits::<impl core::ops::index::Index<I> for str>::index::hc197edec7cb769d4
                               at /rustc/2113659479a82ea69633b23ef710b58ab127755e/src/libcore/str/mod.rs:1780
  18:     0x563bf47a360c - delta::parse::get_file_extensions_from_diff_line::{{closure}}::h605f86cb790f7f20
                               at /home/dahooz/.cargo/registry/src/github.com-1ecc6299db9ec823/git-delta-0.1.1/src/parse.rs:90
  19:     0x563bf47814ad - core::option::Option<T>::and_then::ha4a5b1a852160ca5
                               at /rustc/2113659479a82ea69633b23ef710b58ab127755e/src/libcore/option.rs:670
  20:     0x563bf47a3534 - delta::parse::get_file_extensions_from_diff_line::h520e1d2b89db0b8b
                               at /home/dahooz/.cargo/registry/src/github.com-1ecc6299db9ec823/git-delta-0.1.1/src/parse.rs:90
  21:     0x563bf47a22d5 - delta::parse::get_file_extension_from_diff_line::hd474d36af57452d3
                               at /home/dahooz/.cargo/registry/src/github.com-1ecc6299db9ec823/git-delta-0.1.1/src/parse.rs:7
  22:     0x563bf478a2ce - delta::delta::delta::h4763ff412c69a473
                               at /home/dahooz/.cargo/registry/src/github.com-1ecc6299db9ec823/git-delta-0.1.1/src/delta.rs:84
  23:     0x563bf47cd307 - delta::main::hd143810f70115604
                               at /home/dahooz/.cargo/registry/src/github.com-1ecc6299db9ec823/git-delta-0.1.1/src/main.rs:64
  24:     0x563bf4799c4d - std::rt::lang_start::{{closure}}::hf794bfca89b78eef
                               at /rustc/2113659479a82ea69633b23ef710b58ab127755e/src/libstd/rt.rs:67
  25:     0x563bf4ccdb78 - std::rt::lang_start_internal::{{closure}}::h9628629435f9467b
                               at src/libstd/rt.rs:52
  26:     0x563bf4ccdb78 - std::panicking::try::do_call::he8163086ed9ecc4a
                               at src/libstd/panicking.rs:331
  27:     0x563bf4ccdb78 - std::panicking::try::he633d7dd2c755e9f
                               at src/libstd/panicking.rs:274
  28:     0x563bf4ccdb78 - std::panic::catch_unwind::h4ceabfa3bf55291a
                               at src/libstd/panic.rs:394
  29:     0x563bf4ccdb78 - std::rt::lang_start_internal::hb7b86f6e95a1fcf5
                               at src/libstd/rt.rs:51
  30:     0x563bf4799c17 - std::rt::lang_start::h9f70c5cd4ecc5638
                               at /rustc/2113659479a82ea69633b23ef710b58ab127755e/src/libstd/rt.rs:67
  31:     0x563bf47cf75a - main
  32:     0x7fb5933d4b97 - __libc_start_main
  33:     0x563bf4718e5a - _start
  34:                0x0 - <unknown>
$
```

</p>
</details>  

Original `git diff` shows:
```bash session
$ git diff --cached
diff --git a/strange - file.txt b/strange - file.txt
new file mode 100644
index 0000000..9daeafb
--- /dev/null
+++ b/strange - file.txt        
@@ -0,0 +1 @@
+test
$
```

In case `git diff --cached` is not officially supported, `delta` will create basically the same panic with `git diff` after
```bash
git commit -m "init"
echo "test2" > "strange - file.txt"
git diff
```

### PR DESCRIPTION
**Pull request by pt2121**
Fixes #139

### CODE REVIEW

**Comment by dandavison** [comment]
Hi @pt2121 thanks very much for this!

Did you see #120 where we are trying to handle the `diff.noprefix` flag? For a user with that flag set, the strings won't have `a/` and `b/` prefixes.  Do you have any thoughts about handling that? Does it look like we need to instead start using the lines starting `---` and `+++` (what delta calls "file meta" lines) as the source of the file extension? 

An example is

```
$ git mv src/parse.rs src/pa\ rse.rs
$ git --no-pager diff --cached --no-prefix
diff --git src/pa rse.rs src/pa rse.rs                                                                                                                                                                          
new file mode 100644                                                                                                                                                                                            
index 0000000..dcbea72                                                                                                                                                                                          
--- /dev/null                                                                                                                                                                                                   
+++ src/pa rse.rs

...
```

**Comment by pt2121** [comment]
Yes, sure. I'll look into it.

**Comment by dandavison** [comment]
Thanks!

**Comment by pt2121** [comment]
Hi @dandavison,
I updated my code as you suggested. The `diff.noprefix` flag should be now handled.
Please let me know what you think. Thanks!

File: src/parse.rs [hunk 1]
```diff
@@ -105,21 +88,37 @@ mod tests {
...
+            Some("rs")
+        );
+        assert_eq!(
+            get_file_extension_from_file_meta_line_file_path("wat hello.rs"),
+            Some("rs")
+        );
+        assert_eq!(
+            get_file_extension_from_file_meta_line_file_path("/dev/null"),
+            None
+        );
```
Comment (dandavison) [inline src/parse.rs:121]: Would you mind adding test cases for something like `Makefile` that lacks an extension? (Would it be cleaner for it to be handled by the same code path as `/dev/null`?)

Comment (pt2121) [reply src/parse.rs:121]: Added the test cases. 
`/dev/null` seems to be a special case to me so I made a separate code path for it but if you prefer to handle a file without extension in the same code path, I can make the change.

Comment (dandavison) [reply src/parse.rs:121]: Thanks!

File: src/parse.rs [hunk 2]
```diff
@@ -105,21 +88,49 @@ mod tests {
...
             Some("rs")
         );
+        assert_eq!(
+            get_file_extension_from_file_meta_line_file_path("/dev/null"),
+            None
+        );
+        assert_eq!(
+            get_file_extension_from_file_meta_line_file_path("Makefile"),
+            Some("Makefile")
+        );
```
Comment (dandavison) [inline src/parse.rs:125]: Before I write anything else I want to make it clear that you've already done more than enough for your PR to be merged and it's very helpful, so thank you!

I don't have time right now to do further work on these edge cases myself so I'm just going to make so additional comments on the off chance that you want to double-check my thinking, since it's very helpful to have someone else familiar with this code. 

Would you agree that this test case demonstrates a bug? I wonder if what we should do (in a different PR) is determine (programatically?) the cases where the sublime syntax definition is keyed off the entire filename (like `Makefile`, `Dockerfile`) and otherwise refuse to identify a file extension for random filenames that do not look like `*.foo`. 

```diff
diff --git a/src/parse.rs b/src/parse.rs
index e1a0860..78cea85 100644
--- a/src/parse.rs
+++ b/src/parse.rs
@@ -123,6 +123,11 @@ mod tests {
             get_file_extension_from_file_meta_line_file_path("Makefile"),
             Some("Makefile")
         );
+        // TODO: The fact that the following test passes is perhaps a bug.
+        assert_eq!(
+            get_file_extension_from_file_meta_line_file_path("rs"),
+            Some("rs")
+        );
         assert_eq!(
             get_file_extension_from_file_meta_line_file_path("a/src/Makefile"),
             Some("Makefile")
```

File: src/parse.rs [hunk 3]
```diff
@@ -105,21 +88,49 @@ mod tests {
     use super::*;
 
     #[test]
-    fn test_get_file_extension_from_diff_line() {
+    fn test_get_file_extension_from_marker_line() {
         assert_eq!(
-            get_file_extension_from_diff_line("diff --git a/src/main.rs b/src/main.rs"),
+            get_file_extension_from_marker_line(
+                "--- src/one.rs	2019-11-20 06:47:56.000000000 +0100"
+            ),
```
Comment (dandavison) [inline src/parse.rs:95]: So I believe that there's another bug remaining (not your fault or responsibility!), in that unified diff is still broken for file names with spaces:

```diff
--- "src/pa r se.rs"	2020-05-03 16:40:13.851935846 -0400
+++ "src/pa rse.rs"	2020-05-03 16:41:49.798457052 -0400
@@ -231,4 +231,7 @@
         );
     }
 }
-vjhvjj
+
+pub fn test(s: &str) {
+    println!("hello {}", s);
+}
```

<table><tr><td>image</td></tr></table>

If I remove the double quotes and spaces from those filenames, then delta syntax-highlights the added function as Rust:

```diff
--- src/parse.rs	2020-05-03 16:40:13.851935846 -0400
+++ src/parse.rs	2020-05-03 16:41:49.798457052 -0400
@@ -231,4 +231,7 @@
         );
     }
 }
-vjhvjj
+
+pub fn test(s: &str) {
+    println!("hello {}", s);
+}
```

<table><tr><td>image</td></tr></table>

**Comment by dandavison** [comment]
Thanks a lot for this work. I'll do a final review/test and merge soon.

File: src/parse.rs (hunk 2 above)
Comment (pt2121) [reply src/parse.rs:125]: Oh, I see. Nice catch.
I'm not sure if there is a good way to differentiate them unless we have a list of all file types that don't have an extension e.g. `Makefile`, `Dockerfile`.

Comment (dandavison) [reply src/parse.rs:125]: I was hoping that the sublime syntax definitions might distinguish between genuine extensions, that involve a `.`, like `foo.py`, vs whole-file-name extensions like `Makefile`, `Dockerfile`. However, it looks like they don't. So I don't think this is delta's problem, seeing as bat also suffers from it:

 <table><tr><td>image</td></tr></table>

**Comment by pt2121** [comment]
Have you had a chance to look at this? Anything else I should address in this PR?

**Comment by dandavison** [comment]
> Anything else I should address in this PR?

No, it looks great, thanks very much!

**Comment by pt2121** [comment]
No problem. I will try fixing the remaining bug when having time.
